# hinglish_mapper.py

# This dictionary maps ITRANS-style words to more readable Hinglish.
ITRANS_TO_HINGLISH = {
    "maiM": "main",
    "tum": "tum",
    "aura": "aur",
    "isa": "is",
    "usake": "uske",
    "kya": "kya",
    "nahIM": "nahi",
    "hU~": "hoon",
    "hai": "hai",
    "tha": "tha",
    "kaha": "kaha",
    "batao": "batao",
    "ye": "ye",
    "jo": "jo",
    "vo": "vo",
    "ham": "hum",
    "unka": "unka",
    "mera": "mera",
    "tera": "tera",
    "kyuM": "kyun",
    "kaise": "kaise",
    "koi": "koi",
    "sab": "sab",
    "phir": "phir",
    "sirpha": "sirf",
    "saI": "sahi",
    "acchA": "accha",
    "bahuta": "bahut",
    "bhI": "bhi",
    "kyA": "kya",
    "nahIM": "nahi",
    "kisI": "kisi",
    "karanA": "karna",
    "jA~": "jaoon",
    "bolatA": "bolta",
}
